import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Main from "~/components/Main";
import Aside from "~/components/Aside";
import Container from "~/components/Container";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="aqua">
      <body className={`font-sans ${inter.variable}`}>
        <Main>
          <Aside/>
          <Container>
            { children}
          </Container>
        </Main>
      </body>
    </html>
  );
}
